# fly.toml app configuration file generated for ancient-water-4020 on 2023-11-07T22:13:23-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ancient-water-4020"
primary_region = "iad"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
